//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Techno2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_COMPRA
    {
        public string ID_Detalle_Compra { get; set; }
        public string ID_COMPRA { get; set; }
        public string ID_Producto { get; set; }
        public string precio_compra { get; set; }
        public string precio_venta { get; set; }
        public int Cantidad { get; set; }
    
        public virtual COMPRA COMPRA { get; set; }
        public virtual PRODUCTOS PRODUCTOS { get; set; }
    }
}
