//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Techno2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_VENTA
    {
        public string ID_detalle_venta { get; set; }
        public string ID_venta { get; set; }
        public string Id_Producto { get; set; }
        public int cantidad { get; set; }
        public string Precio_Venta { get; set; }
    
        public virtual PRODUCTOS PRODUCTOS { get; set; }
        public virtual VENTA VENTA { get; set; }
    }
}
